### ISSUE TITLE
Volunteer signup form is outdated

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#1]
It's not a show stopper, but it will cause some confusion for the potential volunteers new to Thunder Plains.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/943398/15517606/3e7ebeee-21be-11e6-80e7-5689ad4918f4.png)

**Comment by amandaharlin** [comment]
i posted this in slack too lol i'll get to it after fixing the devon boathouse link

**Comment by amandaharlin** [comment]
done 👍 https://docs.google.com/forms/d/1FvMkWYfVcyTFYTozbEmW-YXUw1BwLWHJsD8pkoXT65Q
