### ISSUE TITLE
Map marker is on the wrong boathouse. Move to Devon Boathouse.

### ISSUE THREAD

**Issue by vlucas** [techlahoma/thunderplains-2016#13]
Map marker is currently on the Chesapeake Boathouse on the website. Move it to the Devon Boathouse (correct Google Maps image below).

![screenshot 2016-08-22 15 01 28](https://cloud.githubusercontent.com/assets/187/17869533/62905dfe-6879-11e6-823d-d638560807e3.png)

**Comment by DevinClark** [comment]
Fixed in mapbox.
