### ISSUE TITLE
Tour Devon Boathouse to plan registration and swag tables

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#20]

**Comment by seejessicacode** [comment]
@amandaharlin Are you still up for this tomorrow?

**Comment by seejessicacode** [comment]
Amanda and I visited the boat house and were shown around by gentleman named Jarrod.

The "lobby" is a narrow hallway (well narrow compared to Cox Convention Center) and it's also needs space kept clear for the staircase and restrooms on the East wall.

There will also be people (though I don't think there will be a lot) visiting to use the boathouse gym. So any way we spread out will have to mindful of them as well.

The current plan is to use the 1st floor room for the talks and the 2nd floor room for quiet room for speakers, lunch, and after party. 

The 1st floor event room has a lot of natural light but they have shades they can lower.
For presentation displays Jarrod only pointed out three small TVs, though I remember seeing a projector in the 2nd floor room--can't remember if there was one on the first floor.

Jarrod also said we had plenty of options of where to display signage, including outside on the lawn.

Amanda and I are wondering if setting up an event tent outside the entrance would help with space and checking guests in. It would definitely help guests identify which building is the right building.

Jarrod said that the event staff should be contacting TP organizers soon to sort out these details.
Current questions to review with event staff:
- Is there a projector in the first floor event room? If not, may we provide our own?
  - Is there a projection screen we may use? If not, may we provide our own?
- Is there a blue print of the lobby we can reference for planning out how we use the space?
- Can the blue buffalo be removed from lobby hall to make room for a sponsor booth?
- Can we rent an event tent to post outside the boathouse entrance?
- Where can we direct guests who are interested in checking out the ropes course that is a few buildings east?

Am I forgetting anything @amandaharlin?

**Comment by amandaharlin** [comment]
I dont think any sponsors should ve under the staircase. Its not enough room. I dont nind the buffalo bring there

**Comment by amandaharlin** [comment]
We could just purchase a tent for $200 from sam's. that's not a bad idea for techlahoma to have event tents.

**Comment by the-simian** [comment]
We did this last week
