### ISSUE TITLE
Speaker Bio & Talks

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#21]
Can someone update Ben, Lon, and Christina's missing info?

<details>
<summary>

 Ben Ilegbodu </summary>

photo: 
![us1gjrtii1o6uywoqnurxncisp7a773ji8anvlff](https://cloud.githubusercontent.com/assets/716644/18234244/c501e062-72c3-11e6-9276-43af058484c6.jpeg)

Ben's twitter @benmvp

Ben's Bio
Ben is a Christian, a husband and a father with over 10 years of experience developing for the Web. He currently is a Senior UI Engineer on Eventbrite’s Frontend Platform team. On the side, Ben also enjoys playing basketball, watching movies, and blogging (benmvp.com) / tweeting (@benmvp) about his experiences with new web development technologies.

Ben's talk:

JavaScript is evolving quickly. The ES6 specification was released in 2015 and is quickly being implemented by modern browsers. New versions of ECMAScript will now be released on a yearly basis. We can leverage ES6 and functionality slated for future versions right now to write even clearer and more concise React code.

Experience with React will help you get the most out of this session, but you don’t have to have a JavaScript black belt to leave feeling confident in using ES.next with React. Learn how to write cleaner code using the new spread operator, classes, modules, destructuring, and other tasty syntactic sugar features being introduced into ECMAScript. Oh, and don’t worry if you don’t understand all of those terms — you soon will after this session!
</details>

<details>
<summary>

 Lon Ingram </summary>

photo: 
![abqpzqqnuzd7eto7tknekycdks1i8z3ffcm6xyao](https://cloud.githubusercontent.com/assets/716644/18234245/c9bbe18e-72c3-11e6-9780-e2bb96356cc0.jpeg)

Lon's twitter @lawnsea

Lon's Bio:
Lon is a Principal UI Engineer at RetailMeNot. He is fascinated with applying ideas from systems research to the challenge of building cool complicated things on the web.

Lon's talk:

For many years, the JavaScript community and academia regarded each other with a mixture of disinterest and disdain, but as JavaScript became fast and ubiquitous and the JS community tackled more ambitious projects and grappled with harder problems, this changed. This talk will survey the current landscape of academic research related to JavaScript: everything from automatically verifying the correctness of web applications to remotely triggering hardware faults in DRAM via JS. Along the way we'll learn where to find interesting academic papers about the web and how to read them.

</details>

<details>
<summary>

 Christina Keelan </summary>

(needs to be added to day 2 btw) 

photo: 
![7xengrdhw5h15wyhwi9fyckgkysyz9o7wm2oofb0](https://cloud.githubusercontent.com/assets/716644/18234248/ce1a9356-72c3-11e6-8d2b-bf217f063ae8.png)

Christina's twitter - @christinakeelan

Christina's Bio:
Christina is the community manager at RethinkDB, an open-source database that makes easier to build realtime apps, and at Horizon, an open-source realtime backend for JavaScript apps. She studied Fashion Design and Psychology, but loves her new role exploring tech and learning JavaScript. She loves kitties, Mother Earth, space, cooking, and "the art of slow living" :D Go send her cute memes on Twitter @christinakeelan

Christina's talk:

'I made you this mixtape! 😍 -- Building a collaborative music player using Horizon and Angular2'

Building collaborative, realtime apps is a challenge. It's an even bigger challenge when you're new to programming. I wanted to learn to code... but was I biting off more than I could chew? Enter Horizon, an open-source, realtime backend that dramatically simplifies the process of building modern JavaScript apps. As someone with little programming experience who’s just learning to code, I could use Horizon to build real apps!

In this talk, we’ll build Mixtape — an app for sharing playlists. It has all the components of modern applications — frontend, backend, dealing with APIs, etc. Using Horizon's client API, we'll be taking full advantage of Angular2's first-class support for observables. Keeping your views synchronized with the server in realtime has never been easier! We'll tie it all together with the Spotify API, allowing users to browse tracks and import playlists. The icing on the cake -- cheese on the pizza? -- I've got a fun UI for the user to personalize their "mixtape" and share. By the end of the conference, I hope everyone is sending mixtapes to all their friends :D
</details>

**Comment by seejessicacode** [comment]
@DevinClark ?

**Comment by benmvp** [comment]
Thanks!

**Comment by seejessicacode** [comment]
Changes have been tested but not published in #22, do not have access to handle it myself.

**Comment by seejessicacode** [comment]
Changes have been published. I think this was @amandaharlin's doing... Thanks Amanda!

**Comment by amandaharlin** [comment]
it wasn't. bet it was vance! he's been swooping in and taking care of
bizness

**Comment by the-simian** [comment]
oh yay
