### ISSUE TITLE
Lunch & After Party food

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#23]
Big Truck Tacos for day 1?
Back Door BBQ for day 2?
After Party food?

Breakfast?

Breakfast for Speakers?

**Comment by amandaharlin** [comment]
Big Truck Tacos for day 1?
Back Door BBQ for day 2?
After Party food?

Breakfast?

Breakfast for Speakers?

**Comment by the-simian** [comment]
@vlucas  has all of this done, foodwise.

Still actionable: 
- [ ] bartender

**Comment by the-simian** [comment]
closing this since its on the afterparty issue
