### ISSUE TITLE
Pair shirts with name badges (and swag bags?)

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#24]
To speed up check-in.
Current ideas are:
- Roll up shirts with tie them off with lanyard and badge; Leave swag bags on the side as grab and go.
- Pack shirt, badge, lanyard, and remaining swag in packages and label them by guest name.

**Comment by seejessicacode** [comment]
Need to add @carmalou to team so we can assign her also.

**Comment by seejessicacode** [comment]
It'd be ideal to have these done and sorted by Oct 30th, but ticket sales do not stop until Oct 25th. Any tickets sold after then will be at the door.

@amandaharlin when is the soonest we can get the shirts in? Maybe we can pack and sort the shirts first and add additional swag later?

**Comment by amandaharlin** [comment]
we need to call the tshirt place and ask for their schedule. if they can't fit us in that will potentially impact some of our plans.
