### ISSUE TITLE
Build speaker gift bags

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#25]
Gracious hosts that we are, we've always given thank you gifts to our speakers.
- [ ] Budget how much we spend per speaker (10 speakers, not counting panel guests.)
- [ ] Decide what we're giving our speakers.
- [ ] Wrap or bundle gifts, label by speaker if the gifts are tailored per individual.

**Comment by seejessicacode** [comment]
Please pitch ideas. It'd be ideal to have this done by Oct 29.

**Comment by amandaharlin** [comment]
We have TP drawstring bags.

jessica or amanda will need to find this online: bulk aspirin, bulk hand wipes, etc
amanda will purchase these items from sam's: bulk granola bars, bulk water, energy drink shots

**Comment by seejessicacode** [comment]
@amandaharlin How's this list lookin'?

Over the counter:
- Pain/Headache:
  - Aspirin:
    - [Bayer Aspirin 325 mg tablets 100 ct at 50 packs with 2 tablets per pack - $13.25 ($0.27 per pack)](https://www.amazon.com/gp/product/B003AOFNM8/ref=ox_sc_act_title_12?ie=UTF8&psc=1&smid=A3V5KST2MBAC9I)
  - Ibuprofen
    - [Advil Ibuprofen 200 mg tablets 100 ct at 50 packs with 2 tablets per pack - $10.99 ($0.22 per pack)](https://www.amazon.com/gp/product/B0006SW71G/ref=ox_sc_act_title_14?ie=UTF8&smid=ATVPDKIKX0DER&th=1)
  - Acetaminophen
    - [Tylenol Acetaminophen 500 mg caplets 100 ct at 50 packs with 2 caplets per pack - $11.89 ($0.23 per pack)](https://www.amazon.com/gp/product/B0027689XU/ref=ox_sc_act_title_11?ie=UTF8&smid=ATVPDKIKX0DER&th=1)
- Tummy Turmoil
  - [Pepto Bismol chewable tablets 50 ct at 25 packs with 2 tablets per pack - $10.97 ($0.44 per pack)](https://www.amazon.com/gp/product/B0082SZNBS/ref=ox_sc_act_title_9?ie=UTF8&smid=A1L0WTH0TOW7MN&th=1) 

Kleenex:
- [Kleenex® 3-Ply Pocket Packs Facial Tissues 24 packs with 10 tissues per pack -  $11.99 ($0.50 per pack)](https://www.amazon.com/gp/product/B00GT0QWOI/ref=ox_sc_act_title_2?ie=UTF8&psc=1&smid=A1KRI4CSQ591L0)

Hand sanitizing wipes:
- [PURELL Sanitizing Hand Wipes 300 ct at 300 packs with 1 wipe per pack) - $20.05 ($0.07 per pack)](https://www.amazon.com/gp/product/B014EVXZ9S/ref=ox_sc_act_title_1?ie=UTF8&psc=1&smid=ATVPDKIKX0DER)

Energy shots: _(in order of flavor preference)_
- [5 Hour Energy Extra Strength Energy Shots, Berry, 12 pack - $25.76 ($2.15 per unit)](https://www.amazon.com/gp/product/B003QNJYXM/ref=ox_sc_act_title_6?ie=UTF8&smid=ATVPDKIKX0DER&th=1)
- [5 Hour Energy Drink Shot, Berry, 12 pack - $26.12 ($2.18 per unit)](https://www.amazon.com/gp/product/B0029ZAOW8/ref=ox_sc_act_title_8?ie=UTF8&smid=ABUX1LH52S4Z6&th=1)
- [5 Hour Energy Drink Shot, Extra Strength Strawberry Watermelon, 12 pack - $26.59 ($2.22 per unit)](https://www.amazon.com/gp/product/B00P6805PG/ref=ox_sc_act_title_4?ie=UTF8&psc=1&smid=ATVPDKIKX0DER)
- [5 Hour Energy Nutritional Drink, Pink Lemonade, 12 pack - $28.85 ($2.41 per unit)](https://www.amazon.com/gp/product/B00AOKMZRC/ref=ox_sc_act_title_2?ie=UTF8&smid=AKIK8JL6TF2UB&th=1)
- [5 Hour Energy Drink Shot, Citrus Lime, 12 pack - $30.27 ($2.53 per unit)](https://www.amazon.com/gp/product/B006YG4VTA/ref=ox_sc_act_title_5?ie=UTF8&smid=ATVPDKIKX0DER&th=1)
- [5 Hour Energy Energy Shots, Grape, 12 pack - $24.99 ($2.09 per unit)](https://www.amazon.com/gp/product/B003QNLUTI/ref=ox_sc_act_title_3?ie=UTF8&smid=ATVPDKIKX0DER&th=1)
- [5 Hour Energy Energy Shots, Pomegranate, 12 pack - $25.99 ($2.17 per unit)](https://www.amazon.com/gp/product/B003QNLTN0/ref=ox_sc_act_title_1?ie=UTF8&smid=ABUX1LH52S4Z6&th=1)
- [5 Hour Energy Drink Shot, Blueberry, 12 pack - $24.22 ($2.02 per unit)](https://www.amazon.com/gp/product/B016KI9NPS/ref=ox_sc_act_title_7?ie=UTF8&smid=ATVPDKIKX0DER&th=1)

Snacks:
- [Trident Sugar Free Gum Minty Sweet Twist 12 packs with 18 pieces in each pack - $15.88 ($1.33 per pack)](https://www.amazon.com/gp/product/B000ZERFEK/ref=ox_sc_act_title_3?ie=UTF8&psc=1&smid=A2977IQ4POB8VT)
- [Trident Sugar Free Gum Bubblegum flavor 12 packs with 18 pieces in each pack - $10.68 ($0.89 per pack)](https://www.amazon.com/gp/product/B000KOSXI2/ref=ox_sc_act_title_4?ie=UTF8&smid=ATVPDKIKX0DER&th=1)

Additional stuff I thought would be handy:
- [Pdi See Clear Eyeglass cleaning wipes 120 ct - $7.90 ($0.7 per wipe)](https://www.amazon.com/gp/product/B0015TEFU6/ref=ox_sc_act_title_8?ie=UTF8&psc=1&smid=AO5MKE2Z1JRG0)
- [Shout Wipes - Portable Stain Treatin' Wipes 24 ct - $9.15 ($0.39 per wipe)](https://www.amazon.com/gp/product/B00EDW2JC8/ref=ox_sc_act_title_7?ie=UTF8&smid=AH9Z7IIIU8O9I&th=1)

**Comment by amandaharlin** [comment]
JESS DANG!!!!!! 😲😍

**Comment by the-simian** [comment]
will hit this tomorrow on bag duty. we have leftover drawstring bags from last year to put stuff in
