### ISSUE TITLE
Add @camarlou and @blazedd to team

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#26]
Necessary for task assignment.

**Comment by DevinClark** [comment]
Do you know what team they need to be in? I think I can do this.

**Comment by seejessicacode** [comment]
https://github.com/orgs/techlahoma/teams/thunder-plains, I think....

I can now assign @carmalou to this task if I wanted--so yes, I think that team should do it.

**Comment by seejessicacode** [comment]
Looks like I can now assign tasks to @blazedd and @carmalou. Thanks @DevinClark!
