### ISSUE TITLE
Add Lift Security to Bronze Sponsors list

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#27]
Email talk of Adam's employer/company paying his travel expenses which would be about the same cost as a Bronze Sponsor promotion package.

Adam B. said "Node Security" but Amanda said "Lift Security." I just picked that last named reference.
- [ ] Get confirmation from @amandaharlin on company info
- [ ] Make change
- [ ] Submit PR
- [ ] Remind crew in PR that your change is pending confirmation of company payment.

**Comment by amandaharlin** [comment]
We're not certain they're sponsoring atm
