### ISSUE TITLE
Add panelists to site

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#28]
Trisha Salas to wit
Carlos Moreno to civic

And we need everyone's bio too 😱

**Comment by seejessicacode** [comment]
What do you think about just asking everyone to post their bio here?

**Comment by amandaharlin** [comment]
It's not going to get done soon enough. We have to write it, ask them to make any changes if they'd like, and post it.

**Comment by amandaharlin** [comment]
- [ ] Ofi Ochoa photo & bio
- [ ] Carmen Long photo & bio
- [ ] Trisha Salas photo & bio
- [ ] Amanda Harlin photo & bio
- [ ] Catherine Lippert photo & bio
- [ ] Matt Chandler photo & bio
- [ ] Carlos Moreno photo & bio
- [ ] Brittany Bertwanger photo & bio
- [ ] Beth Knight photo & bio

**Comment by amandaharlin** [comment]
Ofi Ochoa is the President of Nerdy Girls, a national organization dedicated to creating intelligent community to empower women. Ofi has run Nerdy Girls Code Club and taught women to code. She is a graphic designer and programmer at Quail Creek Bank. 

![ofi](https://cloud.githubusercontent.com/assets/716644/18619425/75d27d2c-7dc1-11e6-924b-e927ea0e597d.jpg)

**Comment by amandaharlin** [comment]
Carmen Long is the creator of Twister.js, an app that teaches children to code. She has taught at Nerdy Girls Code Club and speaks at OKC.js, 200OK, and Tulsa Tech Fest. Carmen is a JavaScript programmer at Monscierge.

![carmen](https://cloud.githubusercontent.com/assets/716644/18619433/d0dbd330-7dc1-11e6-824e-1592dd5f247f.jpg)

**Comment by amandaharlin** [comment]
@carmalou has already gotten the rest of the bios DONE

DANG!!! 👏 👏 👏 👏 👏  saving the day should be under your bio!

**Comment by amandaharlin** [comment]
Ofi Ochoa --

Ofi is the President of Nerdy Girls, a group for local women to meet and share ideas and creativity. Ofi is also a developer for Quail Creek Bank, and a diehard Star Wars fan.
Twitter: https://twitter.com/ofiwankenobi

Trisha Salas --

Trisha is a developer in Oklahoma City specializing in Wordpress. She is also a member of the Wordpress accessibility team.
Twitter: https://twitter.com/trishacodes

Amanda Harlin --

Amanda is a JavaScript developer located in Norman, Oklahoma. Working toward improving the tech community for local developers, Amanda organizes Thunder Plains and OKCjs. Amanda is also a co-founder of Techlahoma.
Twitter: https://twitter.com/amandaharlin

Catherine Lippert --

Catherine is a developer in Oklahoma City and a co-organizer for Code for OKC. She is a developer and currently works as a project manager for Praeses.
Twitter: https://twitter.com/cahiller

Matt Chandler --

Matt is a developer for Hobby Lobby in Oklahoma City. He is also a co-organizer for Code for OKC and an open-source enthusiast.
Twitter: https://twitter.com/mkchandler

Carlos Moreno --

Carlos is a digital strategist for Dreamclinic Creative, as well as a co-captain of Code for Tulsa. Carlos is also a board member for Smart Growth Tulsa.
Twitter: https://twitter.com/chimchim237

Brittany Bertwanger --
Brittany is a developer located in Tulsa, Oklahoma. She is a member of Tulsa Web Devs, and has spoken at Tulsa Tech Fest.
Twitter: https://twitter.com/brittberwanger

Beth Knight --

Beth is a Rails developer in Tulsa at Shipzen. She is a member of Tulsa Web Devs and built Votebyte, an iOS app to track elections and improve voter turnout.
Twitter: https://twitter.com/bethknight1234

**Comment by carmalou** [comment]
I'll keep looking around and trying to find thing to put into these bios so they are less generic. but this is a good start. :)

**Comment by amandaharlin** [comment]
![catherine](https://cloud.githubusercontent.com/assets/716644/18619540/03ff929e-7dc5-11e6-8f33-9a1a0f07002c.jpg)

![matt](https://cloud.githubusercontent.com/assets/716644/18619541/05314bbc-7dc5-11e6-967a-afcd92b1a618.jpg)

![carlos](https://cloud.githubusercontent.com/assets/716644/18619549/0f0db594-7dc5-11e6-9c2c-0b0d4144d4ff.jpg)

![brittany](https://cloud.githubusercontent.com/assets/716644/18619558/3d9007fa-7dc5-11e6-84d3-8a8c75860e43.jpg)

![beth](https://cloud.githubusercontent.com/assets/716644/18619560/4125d37c-7dc5-11e6-94e4-01b283fcd832.jpg)

![amanda](https://cloud.githubusercontent.com/assets/716644/18619563/4f29c474-7dc5-11e6-8001-abd6619aef96.jpg)

**Comment by amandaharlin** [comment]
Going to add Susan Simkins to WiT tomorrow
