### ISSUE TITLE
Buy t-shirts

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#29]
We need to contact the t-shirt place, ask them for their availability, get the size and amount from ti.to, and re-evaluate the ticket end date. 

Can we print 250 shirts _ON_ october 25th or do we need to end ticket sales early?

**Comment by amandaharlin** [comment]
we need to get the early ticket holders to give us their tshirt sizes. tito offers some email features, so i'm gonna try to send a reminder email.

**Comment by amandaharlin** [comment]
just emailed quantumco about their availability. if they don't respond soon we can go with an online bulk retailer or try someone else local.

**Comment by vlucas** [comment]
Do we not want to go with the same vendor as the previous 2 years?

**Comment by amandaharlin** [comment]
I just called quantumco to see their availability. if hobi can lock it down
then that's fine by me too! whoever can handle this order :+1:

**Comment by amandaharlin** [comment]
just asked t-shirt place if we can do american apparel for S-2XL and next level apparel cvc crew for 3XL. i don't think we want to do tultex due to it's post-wash shrinkage.

**Comment by amandaharlin** [comment]
since we only have six 3XL orders, we could even order these shirts online from a site like customink or vistaprint. customink has the next level apparel too! so, if fulfilling that particular size order via the t-shirt company is a hassle and they can't do it - we'll have a backup plan.

**Comment by the-simian** [comment]
@amandaharlin did this
