### ISSUE TITLE
Arrange speaker hotel

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#32]
- [ ] get the speakers' travel info
- [ ] call back the hotel
- [x] book the hotel rooms
- [ ] pay the hotel.
- [ ] Tell them to NOT charge the speakers' debit cards ('the incidental cards') and to ONLY charge techlahoma

**Comment by seejessicacode** [comment]
Vance booked the hotel for speakers and the Harlin clan
