### ISSUE TITLE
Buy attendee swag bags

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#33]
- [x] buy t-shirts
- [x] get schedule printed
- [x] use or buy bags
- [x] buy stickers

**Comment by amandaharlin** [comment]
i'm ordering some stickers right now.

**Comment by amandaharlin** [comment]
we need #56 to finish before we can do anything. might just re-use old artwork if the student can't finish soon.

**Comment by vlucas** [comment]
We might need to talk about this. I personally dislike swag bags. Is there really a need for us to make them?

**Comment by carmalou** [comment]
@DevinClark @seejessicacode and myself were planning on rolling up t-shirts with nametags pre-conf. could this be done at the same time?

**Comment by seejessicacode** [comment]
Let us know as soon as you know @amandaharlin when most of the shirts will be in so we can set a date for rolling them up and grouping them off by lastname

**Comment by the-simian** [comment]
all that's left are the bags and stuffing them.
