### ISSUE TITLE
Make and Buy outside TP signs

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#34]
we need signs to indicate that _this_ is the conference, this is parking, this is entry, this is tickets. that stuff. we can use signs fast norman or whatever.

**Comment by amandaharlin** [comment]
- [ ] 2 ground-staked signs for car traffic
- [ ] sign outside of event space's entry door
- [ ] sign listing out the schedules
- [ ] sign behind the thunder plains speaker?
- [ ] laminated signs for last name grouping (A-G, H-N, O-U, V-Z)
- [ ] laminated bathroom signs?

**Comment by seejessicacode** [comment]
I took a stab at the last name groups and bathroom signs. 
[Signage.zip](https://github.com/techlahoma/thunderplains-2016/files/549362/Signage.zip)

**Comment by vlucas** [comment]
Thanks @seejessicacode. We have contracted a designer who is finishing up the signs now, but these will work in a pinch in case we can't get them printed or something like that.

**Comment by the-simian** [comment]
@vlucas is following this tomorrow
