### ISSUE TITLE
Figure out A/V

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#35]
the boathouse has mics, but do we want to use them? do they have back up mics available? how are we recording? we need to get cameras rented from bedford audio. do we want a backdrop for speakers #34? then we need to order that too.

**Comment by amandaharlin** [comment]
Ben will be recording. Ava wants a different job besides A/V. so we need to assigned her another task.

**Comment by amandaharlin** [comment]
SS46 needs us to get our projector(s) and screen(s) ready asap. We need to buy these pronto so we can install and use them on Oct 3. Tomorrow I'm going to bring up buying thelse items this week.

**Comment by the-simian** [comment]
This is handled by Ben and Ava @vantreeseba

All the gear is in We're setting it up the night before
