### ISSUE TITLE
Print Schedule for Swag Bag

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#37]
we need to either make the schedule or hire a graphic designer.

**Comment by amandaharlin** [comment]
we need to finish #57

**Comment by vlucas** [comment]
I think we are going to have the schedule rotating on the TV screens instead of a printed one. We MIGHT also print one, but we are not sure at this point.

**Comment by DevinClark** [comment]
That and the website seems sufficient to me.

**Comment by the-simian** [comment]
Ok its ordered and in the mail
