### ISSUE TITLE
Tweet every single week about conf

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#40]
we haven't announced speakers, that 1/2 tickets are gone, that only 6 weeks are left. we need to tweet all these things. post in techlahoma slack too.

**Comment by amandaharlin** [comment]
_EVERY_ week we need to
- [x] announce every speaker
- [x] thank sponsors
- [x] tweet a # of days countdown
- [x] tweet about # of remaining tickets

**Comment by the-simian** [comment]
This is mostly done, just need to add 
- [ ] remarq
- [ ] ocast
- [ ] dynatrace
- [ ] Robert Half
