### ISSUE TITLE
Bring our extra chairs

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#42]
Pick up at least 30 extra chairs from prototek and bring them to the boathouse. we can begin setting up at 7am on day 1 and 8am on day 2.

**Comment by vlucas** [comment]
I think we are going to rent them. The logistics involved with bringing our own will be a nightmare (probably need a moving truck, etc.).

**Comment by amandaharlin** [comment]
sounds good! we'll call some places to get that handled then.

**Comment by amandaharlin** [comment]
i'm having a hard time getting someone to deliver the chairs to the boat house. the stores are considering boathouses to be state property and their liability insurance won't cover delivery to that. so they're offering to let us come pick up the chairs and drop them off, which we could do for free with the techlahoma chairs anyway.

**Comment by amandaharlin** [comment]
another place can do it, but they're going to charge a $300 after hours fee to pick up the chairs
