### ISSUE TITLE
Write CC & WiT Panel Questions

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#43]
## Okla Women Tech Leaders
- can you tell us about yourself?
- what sparked your interest in Tech?
- do you have a traditional CS or Math degree to be employed as a programmer? can people attend bootcamps or learn online and receive the same kind of education? what are some pros and cons to these paths?
- how did you learn to code? would you recommend it to others?
- what are some ways that you connect with other programmers, designers and techies? 
- do you think oklahoma's tech industry is diverse? what about the local software shops? 
- if a company is trying to improve their diversity, what are some ways they can improve interviewing, hiring, and sustaining diverse employees?
- what do you look for when interviewing companies? 
- what was your best and worst experience when interviewing?
- is participating in the tech community a good way to find work, freelance work, or even friends? have you heard or received job offers since you became an active community leader?
- do you have any goals or plans (be it techy, passion project, community or otherwise) for the next 5 years?
- where do you see oklahoma at in the next 5 years?

**Comment by amandaharlin** [comment]
## Okla Civic Hacking
- can you tell us about yourself? 
- what sparked your interest in civic coding?
- do you have a traditional CS or Math 4 year degree to attend civic coding meet ups? who can attend code for tulsa and code for okc? 
- can attendees get real world programming experience from working on these projects?
- what are some ways that you connect with other people (programmers, designers, civic employees or civic-minded folks) and bring them to meetings? 
- can civic hacking make an impact on our local community? 
- can you tell us about your current/previous civic projects, like 1) Tulsa public schools & Tulsa transit CfT project, 2) Votebyte, 3) and the okc financial datavis project?
- do you have any techy, passion project, or community related goals or plans for your next 5 years?
- where do you see oklahoma at in the next 5 years?

**Comment by seejessicacode** [comment]
Excellent questions! I know I was drawing a blank.

**Comment by the-simian** [comment]
These look awesome.  We'll email the panelists tomorrow with them all @amandaharlin I think we might not ask all of these - maybe 5 or so. Depends on length of answere
