### ISSUE TITLE
update website with parking info

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#44]
- [x] get screen cap of the devon boathouse parking areas (directly next to the boathouse and all the nearby lots)
- [x] visually convey that people can park in all those areas 
- [x] put that image on the website

**Comment by the-simian** [comment]
![devin-boathouse-parking](https://cloud.githubusercontent.com/assets/954596/19016621/14da03e0-87e5-11e6-88e5-7083d9bc6ceb.png)
