### ISSUE TITLE
update website with hotel info

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#45]
we can post nearby hotels, like the one we're hopefully going to book, on the website and in our emails

**Comment by seejessicacode** [comment]
- [Residence Inn](http://www.marriott.com/hotels/travel/okcbt-residence-inn-oklahoma-city-downtown-bricktown/)
  - Speaker stays and hotel block are here
- [Hampton Inn](http://hamptoninn3.hilton.com/en/hotels/oklahoma/hampton-inn-and-suites-oklahoma-city-bricktown-OKCBTHX/index.html)
- [Courtyard Marriott](http://www.marriott.com/hotels/travel/okcdt-courtyard-oklahoma-city-downtown/?scid=bb1a189a-fec3-4d19-a255-54ba596febe2)
- [Holiday Inn Express and Suites](https://www.ihg.com/holidayinnexpress/hotels/us/en/oklahoma-city/okcbk/hoteldetail)
- [Renaissance](http://www.marriott.com/hotels/travel/okcbr-renaissance-oklahoma-city-convention-center-hotel/?scid=bb1a189a-fec3-4d19-a255-54ba596febe2)
- [Colcord](http://www.colcordhotel.com)
- [Sheraton](http://www.sheratonokc.com)
- [Skirvin Hilton](http://www.skirvinhilton.com)
- [Aloft](http://www.aloftoklahomacitybricktown.com)

**Comment by seejessicacode** [comment]
@the-simian plans to include a link to the hotel of choice at the bottom page. No frills necessary.
