### ISSUE TITLE
Follow up with Devon Boathouse about setup info

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/thunderplains-2016#54]
Contact Vance first to review questions first.
## Overall Setup
- How much seating do we need for both the Lunch and Conference setups?
## Outdoor Setup
- How many signs do we need outside?
- Are we still considering handling registration outside but with a tented booth?
  - If so, does Devon Boathouse offer tents?
## Registration Setup
- How many tables do we have? How many do we need?
- How many volunteers to a table?
- What signs do we need for registration?
  - Last names starting with...?
  - Thunderplains Registration
  - Bathrooms ->
  - Lunch ->
  - Closed off from Thunderplains guests... (for the gym and training parts of boathouse)
- Registration volunteers need access to Tito for checking in guests, assuming they bring their own laptops.
- Need to stow shirts and name tags in bins. Last discussion we agreed on storing member specific swag in alphabetical groups for quick retrieval at registration.
## Conference Room Setup
- How many chairs?
- How many rows of chairs?
- How many aisles among the chairs?
- Is there a projector screen setup?
- Are we using TVs? If so how many?
## Lunch Setup
- How many tables?
- How many can we seat to a table?
- Where do we setup the food?
- Where do we setup the microphone/floor for lunch sponsors?
## After Party
- Will we use same setup as lunch?
- Aside from food, chairs, and tables, what else do we need?
  - Will there be board games, video games, etc?
  - Will we need a projector or TVs?

**Comment by amandaharlin** [comment]
i don't think they offer tents - but i found some pop up tent/canopy options online for as low as  $60! we have 0 tables, but purchasing some might be smart. we can ask devon boathouse if they will let us use any of their foldable tables. (buying our own though would be great too.)

for conference room setup, devon boathouse said they had 2 tv's. they also have 200 chairs. we need to bring 25-30 over from our own stash. we're bringing our projector. good question - we should ask if they have a screen we can project onto.

for lunch, we can just use the same setup of chairs & projector+mic+podium as the speakers used.

for the after party i'd say we'd keep our projector and their tvs out. (it'll be downstairs, right? --what should we use the upstairs area for? it fits like 96 people!) we can do game tourneys. we have jenga, puzzles, video games, just need folks to set them up. if we want to do a board game library like nejs we'd need volunteers to facilitate that extra work.

**Comment by the-simian** [comment]
this issue has been broken into sub issues and is handled via AV/team and others atm
