### ISSUE TITLE
Afterparty Planning

### ISSUE THREAD

**Issue by vlucas** [techlahoma/thunderplains-2016#60]
We need some volunteer help planning the afterparty. This year is too hectic organizing, planning, and booking the event venue on our own to handle this too. Basically, we can set a budget, and you can do anything you want within that budget.

Some things we did in previous years:
- Dinner (self-serve taco/nacho bar in past years was very cost effective and veggie friendly)
- Drinks (Plan on 3/4 alcoholic drinks, 1/4 other - sodas, coffees, teas, juices, etc.)
- Snacks/desserts
- Music (set playlist, DJ, other, etc.)
- Entertainment (board games, video game consoles, other social games, etc.)

Hours: 6pm - 11pm

Note: As part of the venue booking, we are already paying some security guards as required for serving alcoholic beverages, so that will not come out of this budget.

Ping: @seejessicacode @DevinClark @carmalou

**Comment by amandaharlin** [comment]
We'll need someone to hire bartenders and 3 security guards if we plan on
serving alcohol :-X

**Comment by amandaharlin** [comment]
OH! Vance sounds like you already handled it. Wow!

**Comment by vlucas** [comment]
Yes - the venue requires it, so it was built into the cost of the rental.

**Comment by seejessicacode** [comment]
I think we'll need the following clarified before the volunteers start planning:
- Which room are we setting up the after party?
- How many tables will we have and how many people can sit at a table?
- Do we need any tables and chairs set aside for sponsors?
- How many chairs will we have?
- How many TV's will be there?
- May we use the projector and screen?
- How many tables are available for food and drink?
- Who will serve the alcoholic drinks and where?
- What's the predicted head count of the after party? Based on past patterns, I'd guess 1/3 of conference attendance.
- Is an organizer going to handle the food ordering?
  - taco bar! taco bar! taco bar!

Personally, I thought the first TP after party was perfect! I'd like to work off that, what would you all change about it? @DevinClark @carmalou @vlucas @amandaharlin

**Comment by amandaharlin** [comment]
we've got a tour scheduled for tomorrow so a lot of these question will get answered. (woo!)
- we can make use of both upstairs and downstairs. vance had suggested something like serving the drinks upstairs only.
- We'll have 225 chairs.
- They had 2 TV's available for us to use.
- We're good to use the project and screen and TV's. 
- We have to hire the caterers first before we know who'll be serving. We'll find out tomorrow where they'll be serving drinks at.
- usually 1/2 of the attendees drop off if we change locations for an after party - but since this is in the same spot...that's a harder call to know. i think we can plan for 1/2 to stay.
- Organizers have to handle organizing catering, lol. We're planning on a taco bar like usual. 
- After party tacos leaves the question - what do we serve for Breakfast Day 1, Lunch Day 1, Breakfast Day 2, Lunch Day 2 if we go with taco bar at the after party? There's only like 6 catering options and 5x to feed people @___@

**Comment by seejessicacode** [comment]
> After party tacos leaves the question - what do we serve for Breakfast Day 1, Lunch Day 1, Breakfast Day 2, Lunch Day 2 if we go with taco bar at the after party? There's only like 6 catering options and 5x to feed people @___@

We're doing breakfast too? I figured everyone was on their own for breakfast.

> - We'll have 225 chairs.
> - They had 2 TV's available for us to use.

Will these already be in the downstairs room for the conference itself? Just need to know where things will be so we can plan to move them if needed. Tables too.

**Comment by seejessicacode** [comment]
Does anyone have any concerns aside from financial regarding renting one or two video game consoles and party games (like Nintendo Land, Super Smash Bros., Street Fighter, etc.)

**Comment by amandaharlin** [comment]
sounds great. we should list out the consoles, games, and controllers we'll
have available. oh! and start a playlist too!

**Comment by amandaharlin** [comment]
yes, we're doing breakfast. at least jesse at and i talked about it and we
both said yes.

we'll have the tv's upstairs actually and can use them during the after
party. 225 chairs will be downstairs and recently we decided to order some
more chairs for upstairs.

**Comment by seejessicacode** [comment]
- Alcohol:
  - Will the alcoholic drinks be allowed on both first and second floor, or just on the floor they were served on?
  - Will alcohol be served on the first or second floor?
- Video games:
  - TVs will already be on the second floor for streaming the conference. We can set up @amandaharlin's video game consoles and some of my games upstairs.

**Comment by vlucas** [comment]
Alcoholic drinks will be served on the first floor

**Comment by vlucas** [comment]
As far as where people are allowed to go with them - anywhere inside the building, but NOT outside due to the water hazard, etc.

**Comment by amandaharlin** [comment]
just paid the bartender!
