### ISSUE TITLE
Organize volunteer dinner

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#65]
preferably on 11/1 or before

**Comment by seejessicacode** [comment]
Will this be separate from the speaker dinner?

**Comment by amandaharlin** [comment]
yes. the speaker && volunteer dinner is the first night of the conf. the
volunteer dinner is to go over roles, answer questions, and stuff before
the conf.

**Comment by vlucas** [comment]
Yep. The volunteer dinner will be pretty low-key - just a group of us at a local place going over everything.

**Comment by seejessicacode** [comment]
I vote taco bell!!!

**Comment by vlucas** [comment]
Haha - maybe not quite _THAT_ low key. We'll need a quiet and comfortable place to hash out some stuff ;)

**Comment by seejessicacode** [comment]
OR we can eat at Sam's Club and shop with the organizers for party supplies. That's not quiet though.

**Comment by DevinClark** [comment]
@seejessicacode that is a very efficient idea.

**Comment by amandaharlin** [comment]
i like it. was going to say we could do it over at our house or somewhere in norman

**Comment by amandaharlin** [comment]
(sams club is super close too!)

**Comment by amandaharlin** [comment]
we could meet at starspace and just order a pizza 🤔

**Comment by the-simian** [comment]
we are gonna host it Tuesday evening at our house (jsut after work around 6 or when you can arrive, sooner or later) and also google hangouts. The idea is that there are a few things to be done like organizing shirts, but for the google hangouts part, folks can tune in to know the gameplan for wed, thursday and friday

google hangouts meeting will be 7pm at night. I'll post the meeting invite in the slack channel.

If you end up at our house, we'll order food for ya'll
