### ISSUE TITLE
Assemble Attendee Swag Bag

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/thunderplains-2016#72]
gotta ask jesse when the bags will ship in.

t-shirts are here.

we can go to kinkos to print the schedules, unless @the-simian has finished that already.

**Comment by DevinClark** [comment]
Last I heard we weren't doing printed schedules in favor of the website and the TVs. Is this not the case anymore?

**Comment by amandaharlin** [comment]
I thought we were doing both

**Comment by amandaharlin** [comment]
jesse said tomorrow or wed morning the brochures and bags will be in. he
said wednesday would be good for assembly party

**Comment by seejessicacode** [comment]
I'm off ALL DAY Wednesday. count me in for whatever.

**Comment by amandaharlin** [comment]
WOO! ok i need to send you speaker flight times then! <3 <# <# <3

**Comment by the-simian** [comment]
we're doing both, there's a printed flier and also the screens

**Comment by the-simian** [comment]
[the-proof.pdf](https://github.com/techlahoma/thunderplains-2016/files/562903/the-proof.pdf)
heres what they look like
