### ISSUE TITLE
Ticket widget "Continue" button blocks Cluster quantity field

### ISSUE THREAD

**Issue by vlucas** [techlahoma/thunderplains-2016#8]
Wide (desktop) screen:
![screenshot 2016-08-22 11 55 34](https://cloud.githubusercontent.com/assets/187/17863500/7647061e-685f-11e6-82b2-366dac077083.png)

Small (mobile/device) screen:
![screenshot 2016-08-22 11 56 54](https://cloud.githubusercontent.com/assets/187/17863521/8a63a756-685f-11e6-8d29-9368c9d9b3a7.png)

**Comment by amandaharlin** [comment]
i think it was vance who fixed this, so marking it closed
